name: Allexium
favicon: null
layout_spectrum: 0.7430604044348001
typography_spectrum: 0.16043460345827043
title: Allexium Asset Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#1f326a'
    - '#4e5c88'
    - '#727d9f'
    - '#b8bdcc'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
