name: Allexium Asset Management
favicon: null
layout_spectrum: 0.7430604044348001
typography_spectrum: 0.16043460345827043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7611844202037901
  lightness: 0.893794268136844
  saturation: 0.31939106713980436
  rhythmicContrast: 0.31127178971655667
purpose: []
