name: Allexium
favicon: null
layout_spectrum: 0.50316
typography_spectrum: 1
title: Allexium Asset Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#1f326a'
    - '#4e5c88'
    - '#727d9f'
    - '#b8bdcc'
  brandStrength: 0
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
